import React from 'react';
import Head from 'next/head';
import Typewriter from 'typewriter-effect';
import { BsCodeSlash, BsPersonWorkspace } from 'react-icons/bs';
import { AiFillGithub, AiFillLinkedin, AiFillInstagram, AiFillMail } from 'react-icons/ai';
import { TiTick } from 'react-icons/ti';
import { MdDesignServices } from 'react-icons/md'
import Image from "next/image";
import avatar from '../public/avatar.png';
import { skills } from '@/data';

export default function Home() {
  return (
    <div>
      <Head>
        <title>Developed By Noel</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className="bg-white px-10 font-mono">
        <section className="min-h-screen">
          <nav className=" py-10 mb-12 flex justify-between">
            <h1 className='text-2xl'>Developed by Noel</h1>
            <ul className="flex items-center">
              
              <li>
                <a className="bg-gradient-to-r from-cyan-500 to-teal-400 text-white px-4 py-2 rounded-md ml-8"
                  href="#">About Me</a>
              </li>
            </ul>
          </nav>

          <div className="relative mx-auto flex object-center h-80 w-80  ">
            <Image src={avatar} />
          </div>
          <div className="text-center p-10 py-2">
            <h2 className="text-5xl py-2 text-teal-700 font-medium">Noel Galvin</h2>
            <div className="text-gray-800 text-2xl text-center p-2">
              <Typewriter
                onInit={(typewriter) => {
                  typewriter.typeString("Front-End Web Developer")
                    .callFunction(() => {
                      console.log('String typed out');
                    })
                    .pauseFor(2000)
                    .callFunction(() => {
                      console.log('All strings deleted');
                    })
                    .start();
                }}
              />
            </div>
            <p className="text-md py-5 leading-8 text-gray-700">I'm Noel, a Front-End Web Developer from South London. I have a great passion
              for creating immersive and visually pleasing applications.
              Very well organised, a great problem solver and very high attention to detail.
              Besides developing websites, I'm a very big fan of music, films and American Football.

              I'm very interested in all things front-end and want to work on ambitious projects with amazing people.
            </p>
          </div>
          <div className="text-3xl flex justify-center gap-14 py-1 text-gray-600">
            <AiFillGithub />
            <AiFillLinkedin />
            <AiFillInstagram />
            <AiFillMail />
          </div>
        </section>


        <section className="shadow-lg shadow-gray-500/50">
          <div className="text-7xl flex justify-center text-gray-600">
            <MdDesignServices />
          </div>
          <div className="text-md">
            <h3 className="text-3xl py-5 flex justify-center">Services</h3>
           
            
          </div>
        </section>

        <section className="shadow-lg shadow-teal-500/50">
          <div className="text-7xl flex justify-center text-gray-600">
            <BsCodeSlash />
          </div>
          <div className="text-md">
            <h3 className="text-3xl py-5 flex justify-center">Skills &amp; Technologies</h3>
            <p className="text-md text-center py-1 p-2 leading-8 text-gray-800">
              I am currently at the beginning of my journey into becoming a freelance web developer.
            </p>

            <p className="text-md text-center py-2 leading-8 text-gray-800">
              These are the skills and technologies that I have learnt so far and that I'm progressing daily:
            </p>
            <div className="flex flex-wrap justify-center py-7 lg:w-4/5 sm:mx-auto sm:mb-40 -mx-2">
              {skills.map((skill) => (
                <div key={skill} className="justify-center p-2 sm:w-1/2 w-full">
                  <div className="bg-teal-500 rounded flex p-4 h-full items-center">
                    <TiTick className="text-gray-700 w-6 h-6 flex-shrink-0 mr-4" />
                    <span className="title-font font medium text-white ">
                      {skill}
                    </span>
                  </div>
                </div>
              ))}
            </div>
          </div>
        </section>

        <section className="shadow-lg shadow-teal-500/50 ">
          <div className="text-7xl flex justify-center text-gray-600">
            <BsPersonWorkspace />
          </div>
          <div className="text-md">
            <h3 className="text-3xl py-5 flex justify-center">Projects</h3>
              <p className="text-md text-center py-2 p-2 leading-8 text-gray-800">
                I have worked on my own personal projects, as well as working with talented individuals on a few larger projects, which you can view in the projects section below.
                I want to work with a variety of <span className="text-teal-600">people </span>
                and <span className="text-teal-600">businesses </span>around the world, so we can create beautiful applications.
              </p>

              <p className="text-md text-center py-2 leading-8 text-gray-800">
              Here are my most recent projects:
            </p>
            </div>
            <div className="">
        <div className="max-w-2xl mx-auto grid grid-cols-1 md:grid-cols-2 gap-8 p-2 py-20 pb-40">
          {/* Single card */}
          <a
            href="https://skillmatch-jobs.netlify.app/"
            className="w-full block shadow-2xl p-2"
          >
            <div className="relative overflow-hidden p-7 bottom-10">
              <img
                src="/SkillMatch.gif"
                alt="skillmatch"
                className="transform hover:scale-125 transition duration-2000 ease-out"
              />
              <h3 className="absolute top-5 left-2 text-white text-xl bg-teal-500 rounded-md px-3">
                SkillMatch
              </h3>
              <h4 className="absolute left-2 bottom-1 text-gray-500 font-bold text-xs">
                An application that allows a user to search for jobs based on their skills.
              </h4>
            </div>
          </a>
          <a
            href="https://ngalvin1991.github.io/Code-Quiz/"
            className="w-full block shadow-2xl p-2"
          >
            <div className="relative overflow-hidden  bottom-10">
              <img
                src="/codequiz2.gif"
                alt="skillmatch"
                className="transform hover:scale-125 transition duration-2000 ease-out "
              />
              <h3 className="absolute top-5 left-2 text-white text-xl bg-teal-500 rounded-md px-3">
                Coding Quiz
              </h3>
              <h4 className="absolute left-2 bottom-1 text-gray-500 font-bold text-xs">
              A browser run application allowing the user to answer a variety of questions about coding.
              </h4>
            </div>
          </a>
        </div>
      </div>
    </section>

      </main>
    </div>
  );
}