import React from 'react';
import Head from 'next/head';
import Navbar from '@/components/Navbar';
import Main from '@/components/Main';
import About from '@/components/About';
import Skills from '@/components/Skills';


export default function Home() {
  return (
    <div>
      <Head>
        <title>Developed By Noel</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/" />
      </Head>
      <Navbar />
    <Main />
    <About />
    <Skills />
      </div>
)
      }